import {chromium} from '@playwright/test';
import {createRequire} from 'node:module';
import {writeFile} from 'node:fs/promises';
const require=createRequire(import.meta.url);
const sharp=createRequire(require.resolve('next/package.json'))('sharp');
const browser=await chromium.launch({headless:true});
const errors=[];
async function difference(a,b) {
 const left=await sharp(a).ensureAlpha().raw().toBuffer();
 const right=await sharp(b).ensureAlpha().raw().toBuffer();
 if(left.length!==right.length)throw Error('Image dimensions changed unexpectedly');
 let total=0;for(let i=0;i<left.length;i++)total+=Math.abs(left[i]-right[i]);
 return total/left.length;
}
try {
 const page=await browser.newPage({viewport:{width:1600,height:1000},deviceScaleFactor:1,reducedMotion:'reduce'});
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://localhost:3000',{waitUntil:'domcontentloaded'});
 const canvas=page.locator('[data-hero-logo] canvas');
 await canvas.waitFor({state:'visible',timeout:60000});
 await page.screenshot({path:'/tmp/h3-hero-desktop.png'});
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Desktop overflow');
 const reducedA=await canvas.screenshot();await page.waitForTimeout(500);
 if(await difference(reducedA,await canvas.screenshot())>0.15)throw Error('Reduced-motion logo is moving');
 console.log('Desktop and reduced motion verified');
 await canvas.evaluate(el=>el.getContext('webgl2').getExtension('WEBGL_lose_context').loseContext());
 const fallback=page.locator('[data-hero-logo] img');await fallback.waitFor({state:'visible'});await fallback.evaluate(el=>el.decode());
 console.log('Original SVG fallback decoded');
 // Finish the previously interrupted engineering poster export without changing its design.
 const engineering=page.locator('#engineering [data-engineering-visual]');
 await engineering.scrollIntoViewIfNeeded();await engineering.locator('canvas').waitFor({state:'visible',timeout:60000});
 await engineering.locator('canvas').evaluate(el=>{
   const marker=document.createElement('span');marker.id='poster-marker';
   const host=el.parentElement;host.before(marker);
   const stage=document.createElement('div');stage.id='poster-stage';stage.style.cssText='position:fixed;top:0;left:0;width:1100px;height:800px;z-index:2147483647';
   document.body.append(stage);stage.append(host);
   const style=document.createElement('style');style.id='poster-style';
   style.textContent='html,body{background:transparent!important}body>:not(#poster-stage){visibility:hidden!important}#poster-stage,#poster-stage *{visibility:visible!important}';document.head.append(style);
 });
 await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
 const png=await page.locator('#poster-stage').screenshot({omitBackground:true});
 await writeFile('public/industries/engineering-concept.webp',await sharp(png).webp({quality:93,alphaQuality:100}).toBuffer());
 await page.evaluate(()=>{document.querySelector('#poster-marker').replaceWith(document.querySelector('#poster-stage>div'));document.querySelector('#poster-stage').remove();document.querySelector('#poster-style').remove();});
 console.log('Engineering fallback poster exported');
 await page.close();
 const motionPage=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
 motionPage.on('pageerror',e=>errors.push(e.message));
 await motionPage.goto('http://localhost:3000',{waitUntil:'domcontentloaded'});
 const moving=motionPage.locator('[data-hero-logo] canvas');await moving.waitFor({state:'visible',timeout:60000});
 const entrance=await moving.screenshot();await motionPage.waitForTimeout(2800);
 const settled=await moving.screenshot();
 if(await difference(entrance,settled)<0.05)throw Error('Logo entrance did not change');
 await motionPage.waitForTimeout(1400);
 const loopFrame=await moving.screenshot();
 if(await difference(settled,loopFrame)<0.05)throw Error('Ambient animation is not running');
 const pause=motionPage.getByRole('button',{name:'로고 애니메이션 일시정지'});
 await pause.click();await motionPage.waitForTimeout(200);
 const pausedA=await moving.screenshot();await motionPage.waitForTimeout(800);
 const pausedB=await moving.screenshot();
 const pauseDifference=await difference(pausedA,pausedB);
 if(pauseDifference>0.15)throw Error('Paused logo still changes: '+pauseDifference);
 await motionPage.getByRole('button',{name:'로고 애니메이션 재생'}).click();await motionPage.waitForTimeout(1200);
 if(await difference(pausedB,await moving.screenshot())<0.05)throw Error('Resume did not restart motion');
 console.log('Six-piece entrance, ambient animation, pause and resume verified');
 await motionPage.screenshot({path:'/tmp/h3-hero-motion.png'});
 await motionPage.close();
 const mobile=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1,reducedMotion:'reduce'});
 mobile.on('pageerror',e=>errors.push(e.message));await mobile.goto('http://localhost:3000',{waitUntil:'domcontentloaded'});
 await mobile.locator('[data-hero-logo] canvas').waitFor({state:'visible',timeout:60000});
 await mobile.screenshot({path:'/tmp/h3-hero-mobile.png'});
 if(await mobile.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow');
 console.log('Mobile verified');await mobile.close();
 const en=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1,reducedMotion:'reduce'});
 en.on('pageerror',e=>errors.push(e.message));await en.goto('http://localhost:3000/en',{waitUntil:'domcontentloaded'});
 await en.locator('[data-hero-logo] canvas').waitFor({state:'visible',timeout:60000});
 await en.screenshot({path:'/tmp/h3-hero-en.png'});
 if(await en.locator('[data-home-hero] a').getAttribute('href')!=='/en/products')throw Error('English CTA not localized');
 console.log('English verified');
 if(errors.length)throw Error(errors.join('\n'));
 console.log('PASS: hero desktop/mobile, KR/EN, entrance, ambient loop, pause/resume, reduced motion and fallback.');
} finally {await browser.close();}
